name: test

on:
  push:
    branches:
      - cluster
      - master
      - run-golangci-lint
    paths:
      - '**.go'
      - 'go.*'
      - '.github/workflows/main.yml'
  pull_request:
    branches:
      - cluster
      - master
    paths:
      - '**.go'
      - 'go.*'
      - '.github/workflows/main.yml'

permissions: {}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}


jobs:
  lint:
    name: lint
    permissions:
      contents: read
    # Runs on dedicated runner with extra resources since golangci-lint requires extra memory
    # temporarily run it on ubuntu-latest to run on forks
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Go
        id: go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c  # v6.4.0
        with:
          cache-dependency-path: |
            go.sum
            Makefile
            app/**/Makefile
          go-version-file: 'go.mod'

      - run: go version

      - name: Run check-all
        run: |
          make check-all
          git diff --exit-code
